"""
Higgsfield AI API wrapper.

Higgsfield generates cinematic AI videos from a text prompt + optional
reference image. We use it to produce short-form content (60 s) from
the video scripts generated by VideoAgent.

Docs: https://higgsfield.ai/docs
"""

import time
import httpx
from config.settings import HIGGSFIELD_API_KEY, HIGGSFIELD_API_URL, DRY_RUN


HEADERS = {
    "Authorization": f"Bearer {HIGGSFIELD_API_KEY}",
    "Content-Type":  "application/json",
}


def submit_video(
    prompt:           str,
    duration_seconds: int  = 60,
    style:            str  = "cinematic",
    aspect_ratio:     str  = "16:9",
    reference_image_url: str | None = None,
) -> str:
    """
    Submit a video generation job. Returns the job ID.
    In dry-run mode returns a fake job ID.
    """
    if DRY_RUN:
        print(f"\n[DRY RUN] Higgsfield job would be submitted:")
        print(f"  prompt: {prompt[:200]}{'…' if len(prompt)>200 else ''}")
        print(f"  duration: {duration_seconds}s  style: {style}  aspect: {aspect_ratio}\n")
        return "hf_dry_run_job_000"

    payload = {
        "prompt":           prompt,
        "duration":         duration_seconds,
        "style":            style,
        "aspect_ratio":     aspect_ratio,
    }
    if reference_image_url:
        payload["reference_image"] = reference_image_url

    r = httpx.post(
        f"{HIGGSFIELD_API_URL}/generations",
        headers=HEADERS,
        json=payload,
        timeout=30,
    )
    r.raise_for_status()
    return r.json()["id"]


def get_job_status(job_id: str) -> dict:
    """Poll for job status. Returns dict with 'status' and optionally 'video_url'."""
    if DRY_RUN:
        return {"status": "completed", "video_url": "https://example.com/dry_run_video.mp4"}

    r = httpx.get(
        f"{HIGGSFIELD_API_URL}/generations/{job_id}",
        headers=HEADERS,
        timeout=15,
    )
    r.raise_for_status()
    return r.json()


def wait_for_completion(job_id: str, poll_interval: int = 30, timeout: int = 1800) -> str:
    """
    Poll until job completes. Returns the video URL.
    Raises TimeoutError if it takes longer than `timeout` seconds.
    """
    elapsed = 0
    while elapsed < timeout:
        status = get_job_status(job_id)
        if status["status"] == "completed":
            return status["video_url"]
        if status["status"] == "failed":
            raise RuntimeError(f"Higgsfield job {job_id} failed: {status}")
        time.sleep(poll_interval)
        elapsed += poll_interval
    raise TimeoutError(f"Higgsfield job {job_id} did not complete within {timeout}s")
